version: '3.8'

services:
  user-service:
    build:
      context: ./services/user-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}/users

  student-service:
    build:
      context: ./services/student-service
    ports:
      - "${STUDENT_SERVICE_PORT}:${STUDENT_SERVICE_PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}/students
