version: '3.8'

services:
  user-service:
    build:
      context: ./services/user-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}/userdb
    
  product-service:
    build:
      context: ./services/product-service
    ports:
      - "${PRODUCT_SERVICE_PORT}:${PRODUCT_SERVICE_PORT}"
    environment:
      - MONGO_URI=${MONGO_URI}/productdb