// ID Generator Utilities for consistent prefixed IDs

export const generateRoleId = (): string => {
  const timestamp = Date.now();
  const random = Math.floor(Math.random() * 1000);
  return `R${timestamp}${random}`;
};

export const generateUserId = (): string => {
  // Note: User IDs are typically generated by Clerk
  // This is for cases where you need to generate manually
  const timestamp = Date.now();
  const random = Math.floor(Math.random() * 1000);
  return `USER${timestamp}${random}`;
};
